# doctrine:
#     dbal:
#         url: '%env(resolve:DATABASE_URL)%'

#         # IMPORTANT: You MUST configure your server version,
#         # either here or in the DATABASE_URL env var (see .env file)
#         #server_version: '13'
#     orm:
#         auto_generate_proxy_classes: true
#         naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#         auto_mapping: true
#         mappings:
#             App:
#                 is_bundle: false
#                 type: annotation
#                 dir: '%kernel.project_dir%/src/Entity'
#                 prefix: 'App\Entity'
#                 alias: App
# config/packages/doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                
            univ:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_UNIV)%'

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            univ:
                connection: univ
                # mappings:
                #     Univ:
                #         is_bundle: false
                #         # type: annotation
                #         # dir: '%kernel.project_dir%/src/Entity/Univ'
                #         # prefix: 'App\Entity\Univ'
                #         alias: Univ